class CfgWorlds
{
	class GenericNames
	{
		class BrazilianMen
		{
			class FirstNames
			{
				adriano="Adriano";
				afonso="Afonso";
				benicio="Benicio";
				bento="Bento";
				bernardo="Bernardo";
				bruno="Bruno";
				caio="Caio";
				cristiano="Cristiano";
				damiao="Damiao";
				davi="Davi";
				diego="Diego";
				eduardo="Eduardo";
				emanuel="Emanuel";
				felipe="Felipe";
				flavio="Flavio";
				guilherme="Guilherme";
				gilberto="Gilberto";
				heitor="Heitor";
				henrique="Henrique";
				horacio="Horacio";
				joaquim="Joaquim";
				luciano="Luciano";
				mathues="Mathues";
				manuel="Manuel";
				osvaldo="Osvaldo";
				paco="Paco";
				rafael="Rafael";
				reginaldo="Reginaldo";
				renato="Renato";
				ricardo="Ricardo";
				roberto="Roberto";
				salvador="Salvador";
				santiago="Santiago";
				tiago="Tiago";
				vicente="Vicente";
				vitor="Vitor";
			};
			class LastNames
			{
				aldo="Aldo";
				almeida="Almeida";
				alvares="Alvarez";
				andrade="Andrade";
				batista="Batista";
				benites="Benites";
				caldeira="Caldeira";
				candido="Candido";
				cardosa="Cardosa";
				cesario="Cesario";
				diaz="Diaz";
				domingos="Domingos";
				fagundes="Fagundes";
				felicio="Felicio";
				gabriel="Gabriel";
				gimenes="Gimenes";
				henriques="Henriques";
				inacio="Inacio";
				madureira="Madureira";
				marques="Marques";
				moreira="Moreira";
				nunes="Nunes";
				oliveira="Oliveira";
				ortega="Ortega";
				pereira="Pereira";
				ramires="Ramires";
				ramos="Ramos";
				santana="Santana";
				senna="Senna";
				silva="Silva";
				torres="Torres";
				vargas="Vargas";
			};
		};
	};
};