class CfgWorlds
{
	class GenericNames
	{
		class RomanianMen
		{
			class FirstNames
			{
				adrian="Adrian";
				alexandru="Alexandru";
				alin="Alin";
				andrei="Andrei";
				angel="Angel";
				anton="Anton";
				bogdan="Bogdan";
				catalin="Catalin";
				ciprian="Ciprian";
				claudiu="Claudiu";
				constantin="Constantin";
				cornel="Cornel";
				cristian="Cristian";
				dan="Dan";
				daniel="Daniel";
				darius="Darius";
				dorin="Dorin";
				dragos="Dragos";
				eduard="Eduard";
				emil="Emil";
				florin="Florin";
				gavril="Gavril";
				george="George";
				horatiu="Horatiu";
				ilie="Ilie";
				ioan="Ioan";
				ion="Ion";
				ionel="Ionel";
				iulian="Iulian";
				laurentiu="Laurentiu";
				lucian="Lucian";
				marian="Marian";
				mihai="Mihai";
				nicu="Nicu";
				ovidiu="Ovidiu";
				sabin="Sabin";
			};
			class LastNames
			{
				albulescu="Albulescu";
				andronescu="Andronescu";
				anghel="Anghel";
				antonesei="Antonesei";
				apostol="Apostol";
				armean="Armean";
				avram="Avram";
				barbu="Barbu";
				bejan="Bejan";
				boeru="Boeru";
				bratu="Bratu";
				burcea="Burcea";
				calin="Calin";
				carp="Carp";
				chirila="Chirila";
				ciobanu="Ciobanu";
				constantinescu="Constantinescu";
				cornea="Cornea";
				cristea="Cristea";
				damian="Damian";
				dima="Dima";
				dobrescu="Dobrescu";
				dogaru="Dogaru";
				dumitrescu="Dumitrescu";
				ene="Ene";
				filip="Filip";
				florea="Florea";
				georgescu="Georgescu";
				ionescu="Ionescu";
				lazar="Lazar";
				marin="Marin";
				mihailescu="Mihailescu";
				moldovan="Moldovan";
				neagu="Neagu";
				petrescu="Petrescu";
				popescu="Popescu";
			};
		};	
	};
};